name: pytorch
dependencies:
  - python=3.12
  - pip:
    - torch
    - torchvision
    - torchaudio
    - torchmetrics
    - tensorboard
    - matplotlib
    - pandas
    - timm
    - tqdm
    - yacs
    - termcolor

